/* NEXT */
import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";
import { headers } from 'next/headers';

/* COMPONENTS */
import Header from "@/components/navigation/Header";
import Footer from "@/components/navigation/Footer";
import FloatingActionButton from "@/components/navigation/FloatingActionButton";
/* FUNCTIONS */
import { translate } from "@/functions/translate";

/* ASSETS */
import logo from "@/assets/global/logo.svg";

const manrope = Manrope({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
  params: Promise<{
    lang: string;
  }>;
}

export default async function RootLayout({ children, params }: LayoutProps) {
  const { lang } = await params;

  const headersList = await headers();
  const header_url = headersList.get('x-url') || "";
  const navItems = [
    {
      href: `/${lang}`,
      label: translate("1635f5c3-7f8a-42cd-a3b2-444c279f0b7c", lang),
      active: header_url.endsWith(`/${lang}`),
    },
    {
      href: `/${lang}/general-accounting`,
      label: translate("9e52e1ec-ec33-4e9b-a6f8-6b9165411c1f", lang),
      active: header_url.endsWith(`/${lang}/general-accounting`),
    },
    {
      href: `/${lang}/about`,
      label: translate("2ce9c735-c131-40bb-833d-5f1d16447c1c", lang),
      active: header_url.endsWith(`/${lang}/about`),
    },
    {
      href: `/${lang}/contact`,
      label: translate("34db7e00-fd9d-44bd-9a7c-a16c9341c8f1", lang),
      active: header_url.endsWith(`/${lang}/contact`),
    },
  ];

  return (
    <html lang={lang} className="scroll-smooth">
      <body className={`${manrope.variable} antialiased`}>
        <Header
          lang={lang}
          logo={logo}
          elements={navItems}
        />
        {children}
        <Footer lang={lang} />
        <FloatingActionButton />
      </body>
    </html>
  );
}
